Easy functions
alexhutman/zftools pull request #7
Opened 2024-07-16 01:02 UTC by alexhutman

Added functions to do the busywork of constructing the metagraph and
running `dijkstra()` on it. Updated DijkstraMetagraphTestbed to use
`zero_forcing_set()`.

Did not create tests for these functions as they are fairly simple, and would just ~2x the time it takes to test for no reason. It would also be hard to add profiling if we made the tests use these instead of manually setting everything up. We only want to profile the most important part -- `dijkstra()`.

Also, we should probably tweak the module scheme. I'm not too sure where these should go, perhaps the base module (`zeroforcing`)? They seem kind of out of place here.

2024-07-16 01:06 UTC, alexhutman commented
@ldeaett, do you want to try creating a [new "Issue"](https://github.com/alexhutman/ZeroForcingNumber/issues/new) for us to revisit the module naming schema maybe in general, but most importantly, for these new functions? If you do, please [reference](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests) this pull request in the newly created issue!

2024-07-16 01:08 UTC, alexhutman commented on zeroforcing/metagraph.pyx
> +
Do you think this function is even necessary? IMO, it should be pretty self-explanatory for them to get the zero forcing number if we just give them `zero_forcing_set()`.

2024-07-17 00:36 UTC, ldeaett commented on zeroforcing/metagraph.pyx
> +
I don't think it's strictly necessary, but I think it will provide some worthwhile convenience.

2024-07-17 11:36 UTC, ldeaett requested changes
Looks good to me!

2024-07-17 15:45 UTC, alexhutman commented on DijkstraMetagraphTestbed.ipynb
> +    "## Pick a graph, any graph!\n"
Fixes https://github.com/alexhutman/ZeroForcingNumber/pull/7#pullrequestreview-2182660763

2024-07-17 17:02 UTC, alexhutman commented on DijkstraMetagraphTestbed.ipynb
> +    "## Pick a graph, any graph!\n",
Fixes https://github.com/alexhutman/ZeroForcingNumber/pull/7#pullrequestreview-2182660763. I combined those 2 typographical commits into 1.

2024-07-17 17:04 UTC, alexhutman commented on DijkstraMetagraphTestbed.ipynb
> +    "## Pick a graph, any graph!\n"
Fixes https://github.com/alexhutman/ZeroForcingNumber/pull/7#pullrequestreview-2182660763. I combined those 2 typographical commits into 1 also.

2024-07-17 17:18 UTC, ldeaett approved these changes

2024-07-18 03:36 UTC, merged